config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :restaurants

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:success] = "New restaurant saved successfully!"
      redirect_to @restaurant
    else
      flash[:danger] = "New restaurant wasn't saved. Please try again."
      render 'new'
    end
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :description)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LunchRoulette</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Description</th>
    <th></th>
  </tr>
 
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.description %></td>
      <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
    </tr>
  <% end %>
</table>

<br>
<%= link_to 'Add new restaurant', new_restaurant_path %>
<br>
<%= link_to 'Back to homepage', welcome_index_path %>

app/views/restaurants/new.html.erb
<h1>Add new restaurant</h1>

<%= form_with scope: :restaurant, url: restaurants_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back to all restaurants', restaurants_path %>
<br>
<%= link_to 'Back to homepage', welcome_index_path %>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
 
<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<%= link_to 'Back', restaurants_path %>

app/views/welcome/index.html.erb
<h1>Lunch Roulette</h1>

<%= link_to 'Add new restaurant', new_restaurant_path %>
<br>
<%= link_to 'All restaurants', restaurants_path %>